version: '3.9'
services: 
    java-maven-app:
      image: umeshsurya01/demo-app:java-maven-1.0
      ports:
        - 8080:8080
    postgres:
      image: postgres:13
      ports:
         - 5432:5432
      environment:
        - POSTGRES_PASSWORD:my-pwd
        
